---
name: Update mise tool versions
author: PrefectHQ
description: This action will upgrade tools managed by mise and open a PR.

inputs: {}

runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        # This should be 'main' anyway as it will run
        # on a schedule, but let's be explicit so we can,
        # for example, run this from pull request branches.
        ref: 'main'

    - name: install mise
      uses: jdx/mise-action@v2

    - name: upgrade tools in mise
      run: mise upgrade --bump
      shell: bash

    - name: determine if there are changes
      run: |
        if [[ $(git diff --name-only | wc -l) -eq 0 ]]; then
          echo "No changes detected, exiting"
          echo "CHANGES=false" >> $GITHUB_ENV
          exit 0
        else
          echo "CHANGES=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: configure git
      if: env.CHANGES == 'true'
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      shell: bash

    - name: determine branch name
      if: env.CHANGES == 'true'
      run: |
        echo "BRANCH_NAME=mise-updates-$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      shell: bash

    - name: commit and push changes
      if: env.CHANGES == 'true'
      run: |
        git checkout -b $BRANCH_NAME
        git add .mise.toml
        git commit -m 'Update mise tool versions'
        git push --set-upstream origin $BRANCH_NAME
      shell: bash

    - name: create pull request
      if: env.CHANGES == 'true'
      run: |
        gh pr create \
          --base main \
          --title "Update mise tool versions" \
          --label automated-dependency-updates
      env:
        # Required for the `gh` CLI
        GH_TOKEN: ${{ github.token }}
      shell: bash
